//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmYield
    {
        public int YieldID { get; set; }
        public System.DateTime YieldDate { get; set; }
        public int PondID { get; set; }
        public decimal PoundsYielded { get; set; }
        public decimal PoundsPlant { get; set; }
        public decimal PoundsHeaded { get; set; }
        public decimal PercentYield { get; set; }
        
    
        public virtual Pond Pond { get; set; }
    }
}
