//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmYieldHeader
    {
        public int FarmYieldHeaderID { get; set; }
        public System.DateTime YieldDate { get; set; }
        public Nullable<decimal> PlantWeight { get; set; }
        public Nullable<decimal> WeighBacks { get; set; }
    }
}
