//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGApp.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftEnd
    {
        public int ShiftEndID { get; set; }
        public System.DateTime ShiftDate { get; set; }
        public Nullable<int> RegEmpLate { get; set; }
        public Nullable<int> RegEmpOut { get; set; }
        public Nullable<int> RegEmplLeftEarly { get; set; }
        public Nullable<int> TempEmpOut { get; set; }
        public Nullable<int> InmateLeftEarly { get; set; }
        public Nullable<System.DateTime> FinishedKill { get; set; }
        public Nullable<System.DateTime> FinishedFillet { get; set; }
        public Nullable<System.DateTime> FinishedSkinning { get; set; }
        public Nullable<System.DateTime> DayFinishedFreezing { get; set; }
        public Nullable<System.DateTime> NightFinishedFreezing { get; set; }
        public Nullable<decimal> DayShiftFroze { get; set; }
        public Nullable<decimal> NightShiftFroze { get; set; }
        public Nullable<decimal> FilletScaleReading { get; set; }
    }
}
